name: ccount
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aicsimageio=4.10.0=pyhd8ed1ab_1
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.9=hd590300_0
  - amply=0.1.6=pyhd8ed1ab_0
  - anyio=4.5.0=pyhd8ed1ab_0
  - aom=3.6.1=h59595ed_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h01eb140_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - asttokens=3.0.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_2
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attmap=0.13.2=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-auth=0.7.3=h28f7589_1
  - aws-c-cal=0.6.1=hc309b26_1
  - aws-c-common=0.9.0=hd590300_0
  - aws-c-compression=0.2.17=h4d4d85c_2
  - aws-c-event-stream=0.3.1=h2e3709c_4
  - aws-c-http=0.7.11=h00aa349_4
  - aws-c-io=0.13.32=he9a53bd_1
  - aws-c-mqtt=0.9.3=hb447be9_1
  - aws-c-s3=0.3.14=hf3aad02_1
  - aws-c-sdkutils=0.1.12=h4d4d85c_1
  - aws-checksums=0.1.17=h4d4d85c_1
  - aws-crt-cpp=0.21.0=hb942446_5
  - aws-sdk-cpp=1.10.57=h85b1a90_19
  - babel=2.16.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bcrypt=4.2.0=py38h4005ec7_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - blosc=1.21.5=h0f2a231_0
  - bokeh=3.1.1=pyhd8ed1ab_0
  - boto3=1.35.72=pyhd8ed1ab_0
  - botocore=1.35.99=pyge38_1234567_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py38hfa26641_9
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.4=hb9d3cd8_0
  - c-blosc2=2.12.0=hb4ffafa_0
  - ca-certificates=2025.1.31=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.5.0=pyhd8ed1ab_0
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - cfitsio=4.2.0=hd9d235c_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-default-group=1.2.4=pyhd8ed1ab_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.9=h1d3f3f2_0
  - coin-or-clp=1.17.10=h07f2a63_0
  - coin-or-osi=0.108.11=h6514dde_1
  - coin-or-utils=2.11.12=h99da652_1
  - coincbc=2.10.12=1_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - contourpy=1.1.1=py38h7f3f72f_1
  - cryptography=42.0.2=py38he241bfc_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cytoolz=0.12.3=py38h01eb140_0
  - dask=2023.5.0=pyhd8ed1ab_0
  - dask-core=2023.5.0=pyhd8ed1ab_0
  - datrie=0.8.2=py38h01eb140_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.5=py38h6d02427_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2023.5.0=pyhd8ed1ab_0
  - docformatter=1.7.5=pyhd8ed1ab_1
  - docutils=0.20.1=py38h578d9bd_3
  - dpath=2.2.0=pyha770c72_0
  - dropbox=12.0.2=pyhd8ed1ab_0
  - eido=0.2.4=pyhd8ed1ab_0
  - elementpath=4.5.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.4=h5888daf_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=6.1.0=gpl_h334edf3_100
  - filechunkio=1.8=py_2
  - flatbuffers=23.5.26=h59595ed_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py38h2019614_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freeglut=3.2.2=hac7e632_2
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py38h01eb140_0
  - fsspec=2024.10.0=pyhff2d567_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gast=0.4.0=pyh9f0ad1d_0
  - geos=3.12.2=he02047a_1
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.82.2=h07242d1_1
  - glib-tools=2.82.2=h4833e2c_1
  - glog=0.6.0=h6f12383_0
  - gmp=6.3.0=hac33072_2
  - gnutls=3.7.9=hb077bed_0
  - google-api-core=2.22.0=pyhd8ed1ab_0
  - google-api-python-client=2.151.0=pyhff2d567_0
  - google-auth=2.35.0=pyhff2d567_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - google-cloud-core=2.4.1=pyhd8ed1ab_0
  - google-cloud-storage=2.18.2=pyhff2d567_0
  - google-crc32c=1.1.2=py38hf9d55a7_5
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - google-resumable-media=2.7.2=pyhd8ed1ab_1
  - googleapis-common-protos=1.65.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h59595ed_1003
  - grpcio=1.54.3=py38h8dc9893_0
  - gst-plugins-base=1.22.5=hf7dbed1_0
  - gstreamer=1.22.5=h98fc4e7_0
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py38hc4a6f91_101
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf5=1.14.1=nompi_h4f84152_100
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.7=pyh29332c3_1
  - httplib2=0.22.0=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - humanfriendly=10.0=pyhd8ed1ab_6
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.10=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py38hd710160_2
  - imageio=2.36.0=pyh12aca89_1
  - imageio-ffmpeg=0.5.1=pyhd8ed1ab_0
  - imgaug=0.4.0=pyhd8ed1ab_1
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.2=pyh41d4057_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jasper=4.0.0=h32699f2_1
  - jax=0.4.13=pyhd8ed1ab_0
  - jaxlib=0.4.12=cpu_py38hb25f6ba_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py38h578d9bd_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.3.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keras=2.12.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_1
  - lazy_loader=0.4=pyhd8ed1ab_1
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.43=h712a8e2_2
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.1.3=h59595ed_0
  - libarrow=12.0.1=hb87d912_8_cpu
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.1=hc9aadba_0
  - libavif=0.11.1=h5eee18b_0
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20240808=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libglib=2.82.2=h2ff4ddf_1
  - libglu=9.0.0=hac7e632_1003
  - libgomp=14.2.0=h77fa898_1
  - libgoogle-cloud=2.12.0=hac9eb74_1
  - libgpg-error=1.51=hbd13f7d_1
  - libgrpc=1.54.3=hb20ce57_0
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=20_linux64_openblas
  - liblapacke=3.9.0=20_linux64_openblas
  - libllvm15=15.0.7=h5cf9203_3
  - liblzma=5.6.3=hb9d3cd8_1
  - liblzma-devel=5.6.3=hb9d3cd8_1
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.18=h4ab18f5_2
  - libogg=1.3.5=h4ab18f5_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopencv=4.7.0=py38h2f1dfbd_6
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.46=h943b412_0
  - libpq=15.4=hfc447b1_2
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.48.0=hee588c1_1
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libsystemd0=256.9=h2774228_0
  - libtasn1=4.19.0=h166bdaf_0
  - libthrift=0.18.1=h8fd135c_2
  - libtiff=4.5.1=h8b53f26_1
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_2
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.6.0=h5d7e998_0
  - libxml2=2.11.5=h0d562d8_0
  - libxslt=1.1.37=h0054252_1
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - locket=1.0.0=pyhd8ed1ab_0
  - logmuse=0.2.8=pyhd8ed1ab_0
  - lxml=4.9.3=py38h0ef1326_1
  - lz4=4.3.3=py38hdcd8cb4_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.7.3=py38h578d9bd_0
  - matplotlib-base=3.7.3=py38h58ed7fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - ml_dtypes=0.2.0=py38h53bb729_2
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.0.8=py38hea7755e_0
  - multidict=6.0.5=py38h01eb140_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhff2d567_2
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.1=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.36=h5888daf_0
  - nss=3.107=hdf54f9c_0
  - numcodecs=0.12.1=py38h854fd01_1
  - numpy=1.24.4=py38h59b608b_0
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - ome-types=0.5.3=pyhd8ed1ab_0
  - ome-zarr=0.9.0=pyhd8ed1ab_0
  - opencv=4.7.0=py38h578d9bd_6
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.7=hb9d3cd8_0
  - opt_einsum=3.4.0=pyhd8ed1ab_0
  - orc=1.9.0=h2f23424_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.0.3=py38h01efb38_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.1=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.44=hba22ea6_2
  - peppy=0.40.7=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.0=py38h885162f_0
  - pint=0.21=pyhd8ed1ab_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.44.2=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - pooch=1.8.2=pyhd8ed1ab_0
  - prettytable=3.11.0=pyhd8ed1ab_0
  - prometheus_client=0.21.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - proto-plus=1.25.0=pyhd8ed1ab_0
  - protobuf=4.21.12=py38h8dc9893_0
  - psutil=6.0.0=py38hfb59056_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulp=2.7.0=py38h578d9bd_1
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - py-opencv=4.7.0=py38h0df68fb_6
  - pyarrow=12.0.1=py38h39356d1_8_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pyasn1-modules=0.4.1=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=1.10.17=py38h2019614_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py38h01eb140_3
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyqt=5.15.9=py38hffdaa6c_5
  - pyqt5-sip=12.12.2=py38h17151c0_5
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.4=pyhd8ed1ab_0
  - python=3.8.18=hd12c33a_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-irodsclient=2.1.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=5_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.4.1=py38h7f0c24c_1
  - pyyaml=6.0.2=py38h2019614_0
  - pyzmq=26.2.0=py38h6c80b9a_0
  - qt-main=5.15.8=h7fe3ca9_15
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - resource_backed_dask_array=0.1.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.9.4=pyhd8ed1ab_0
  - rpds-py=0.20.0=py38h4005ec7_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruff=0.6.2=py38h3b76349_0
  - s2n=1.3.49=h06160fa_0
  - s3transfer=0.10.4=pyhd8ed1ab_0
  - scikit-image=0.21.0=py38h17151c0_0
  - scikit-learn=1.3.2=py38ha25d942_2
  - scipy=1.10.1=py38h59b608b_3
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - shapely=2.0.6=py38hc5a1e7d_0
  - sip=6.7.12=py38h17151c0_0
  - six=1.16.0=pyh6c4a22f_0
  - slacker=0.14.0=py_0
  - smart_open=7.0.5=pyhd8ed1ab_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=7.32.4=hdfd78af_1
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - snappy=1.1.10=hdb0a2a9_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38h7f0c24c_0
  - stone=3.3.2=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - svt-av1=1.7.0=h59595ed_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tblib=3.0.0=pyhd8ed1ab_0
  - tensorboard=2.12.3=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38hcdda232_1
  - tensorflow=2.12.1=cpu_py38h66f0ec1_0
  - tensorflow-base=2.12.1=cpu_py38h92f4423_0
  - tensorflow-estimator=2.12.1=cpu_py38h27d0da5_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tifffile=2023.2.28=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - toposort=1.10=pyhd8ed1ab_0
  - tornado=6.4.1=py38hfb59056_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20241003=pyhff2d567_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - ucx=1.14.1=h64cca9d_5
  - unicodedata2=15.1.0=py38h01eb140_0
  - untokenize=0.1.1=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - wrapt=1.16.0=py38h01eb140_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xarray=2022.11.0=py38h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xmlschema=3.4.3=pyhd8ed1ab_1
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.5=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xsdata=24.3.1=pyhd8ed1ab_0
  - xyzservices=2025.1.0=pyhd8ed1ab_0
  - xz=5.6.3=hbcc6ac9_1
  - xz-gpl-tools=5.6.3=hbcc6ac9_1
  - xz-tools=5.6.3=hb9d3cd8_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py38h01eb140_0
  - yte=1.5.6=pyha770c72_0
  - zarr=2.17.1=pyhd8ed1ab_0
  - zeromq=4.3.5=h75354e8_4
  - zfp=1.0.1=h5888daf_2
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.0.7=h0b41bf4_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aicspylibczi==3.2.1